### PR TITLE
correct names of the resource classes

### PR DESCRIPTION
**Pull request by muvaf**

### CODE REVIEW

**Review by jbw976 — COMMENTED** [review]
Does any documentation/guides/examples need to be updated along with this?

Were things completely broken before this change, or is this just a cleanup that does not have functional impact?

**Comment by muvaf** [comment]
@jbw976 This is purely a UI change. Though if there is an existing Minimal GCP installation and you're updating it, controller would create new one resource classes instead of patching the existing ones since names will be different. So, I don't think anything bad will happen.

**Review by jbw976 — APPROVED** [review]

**Comment by jbw976** [comment]
LGTM @muvaf, feel free to merge :)

**Review by suskin — APPROVED** [review]
Looks good to me! :squid:

**Pull request merged**
